package com.cq.agent.client.download;

public enum DownloadTaskStatus {

    PREPARED,
    SCANNED,
    INIT_DOWNLOADING,
    INIT_DOWNLOAD_COMPLETED,
    DOWNLOADING_CHUNKS,
    DOWNLOAD_CHUNKS_COMPLETED,
    MERGING_CHUNKS,
    MERGE_CHUNKS_COMPLETED,
    VERIFYING_CHUNKS,
    VERIFY_CHUNKS_COMPLETED,
    DOWNLOAD_SUCCESS,
    FAILED
}