Args=--no-fallback \
       -H:+ReportExceptionStackTraces \
       -H:+UnlockExperimentalVMOptions \
       --initialize-at-build-time=org.slf4j,org.apache.commons.exec \
       --initialize-at-run-time=ch.qos.logback,io.netty,org.quartz,com.google.inject \
       -H:IncludeResources=logback.xml|agent.properties|quartz.properties|META-INF/services/.* \
       -H:+AddAllCharsets \
       --enable-url-protocols=http,https