# H2 数据库配置 (Standalone Mode)
spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  datasource:
    # 多进程访问
    url: jdbc:h2:file:/tmp/my-panel/admin/data/h2.db;MODE=MySQL;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;INIT=CREATE ALIAS IF NOT EXISTS FIND_IN_SET FOR "com.cq.panel.admin.server.common.utils.StringUtils.findInSet"

    # 单进程访问
    # url: jdbc:h2:file:/tmp/my-panel/admin/data/h2.db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE ALIAS IF NOT EXISTS FIND_IN_SET FOR "com.cq.panel.admin.server.common.utils.StringUtils.findInSet"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
